// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID                pgtype.UUID
	Content           []byte
	WhiteboardContent []byte
	Name              string
	IsAnyoneAllowed   bool
}

type SessionToUserMapping struct {
	ID        int32
	SessionID pgtype.UUID
	IsAdmin   bool
	UserEmail string
}

type User struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	Username  string
	Email     string
	Password  pgtype.Text
}
