// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateSessionContent = `-- name: UpdateSessionContent :exec
UPDATE "sessions"
SET content = $2
WHERE id = $1
`

type UpdateSessionContentParams struct {
	ID      pgtype.UUID
	Content []byte
}

func (q *Queries) UpdateSessionContent(ctx context.Context, arg UpdateSessionContentParams) error {
	_, err := q.db.Exec(ctx, updateSessionContent, arg.ID, arg.Content)
	return err
}
